In [3]:
from numpy import *

a = arange(0,20,5)
b = arange(1,5)

print(a)
print(b)

[ 0  5 10 15]
[1 2 3 4]


In [7]:
c = a - b
print(c)
c = a + b
print(c)

c = b**2
print(c)
c = a * b #elementwise product
print(c)
c= a * sin(b)
print(c)



[-1  3  7 11]
[ 1  7 13 19]
[ 1  4  9 16]
[ 0 10 30 60]
[  0.           4.54648713   1.41120008 -11.35203743]


In [9]:
A = array([[1,1],[0,1]])
B = array([[2,0],[3,4]])
c = A*B  #Elementwise product
print(" " ,c)
c = A @ B #Matrix Product
print(" " ,c)
c = A.dot(B)
print(" " ,c) #Matrix product


  [[2 0]
 [0 4]]
  [[5 4]
 [3 4]]
  [[5 4]
 [3 4]]


In [11]:
a = random.random((2,3))
print(a)
c = a.sum() # sum of all elements
print(c)

c = a.max()
print(c)

c = a.min()
print(c)

[[0.27658997 0.64660696 0.71413428]
 [0.8549967  0.63891694 0.12405065]]
3.2552954987448532


In [18]:
a = arange(0,12).reshape((3,4))
print(a)

c = a.max(axis=0)
print("max of each column = " , c)

c = a.min(axis=1)
print("min of each row = ", c)

c = a.cumsum(axis=1)
print("cumulative sum along each row : \n " , c)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
max of each column =  [ 8  9 10 11]
min of each row =  [0 4 8]
cumulative sum along each row : 
  [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [20]:
# Universal functions like sin, cos ,sqrt, exp and etc... are operate elementwise on array
# List of Universal functions :
'''all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil,
 clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, 
 lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, 
 sort, std, sum, trace, transpose, var, vdot, vectorize, where'''

print(sqrt(a))
print(exp(a))

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [28]:
#  arrays can be indexed, sliced and iterated over
a = arange(0,10) ** 2

print(a)
print(a[2])
print(a[2:5])
a[0:6:2] = -1000  # from 0 to 6 set every 2nd element (2 ta 2 ta boro jolo) to -1000 
print(a)
a = a[ : :-1] # reverse a
print(a)

for i in a:
    print(i**(1/3.))

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 4  9 16]
[-1000     1 -1000     9 -1000    25    36    49    64    81]
[   81    64    49    36    25 -1000     9 -1000     1 -1000]
4.3267487109222245
3.9999999999999996
3.6593057100229713
3.3019272488946263
2.924017738212866
nan
2.080083823051904
nan
1.0
nan


/home/armin/App/anaconda3/envs/newKeras/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in power
  del sys.path[0]


In [39]:
 def f(x,y):
     return 10*x+y
 b = fromfunction(f,(5,4),dtype=int)
 print(b)
 
 # first row ( x = 0 and y = 0,1,2,3 ) = 10*x + y = 0,1,2,3
 # second row ( x = 1 and y = 0,1,2,3 ) = 10*x + y = 10,11,12,13
 # .
 # .
 # last row ( x = 4 and y = 0,1,2,3 ) = 10*x + y = 40,41,42,43
 print()
 print(b[0:5, 1])                       # each row in the second column of b
 print(b[ : ,1])                        # equivalent to the previous example
 print(b[1:3, : ])                      # each column in the second and third row of b
 print( b[-1])                                  # the last row. Equivalent to b[-1,:])
 
for i in b.flat:   # b.flat is an object
    print(i)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [49]:
a = 10 * random.random((4,6))
print(a)
print("\n\n")

print(a.ravel() ) # returns the array, flattened
print("\n\n")
print(a.reshape(12,2)) # return new reshaped array
print("\n\n")
print(a.resize((6,4))) # modify and reshape the array itself

[[1.82362019 0.04312125 4.32395491 1.74324053 7.09584695 4.57134785]
 [5.38736406 5.29680198 9.80027554 8.2069501  2.33240057 4.59454927]
 [0.37549235 8.90259048 1.27765998 5.94695691 6.53315793 1.8542774 ]
 [1.79750692 6.9517947  4.03132715 5.06340852 3.59561001 9.53295442]]



[1.82362019 0.04312125 4.32395491 1.74324053 7.09584695 4.57134785
 5.38736406 5.29680198 9.80027554 8.2069501  2.33240057 4.59454927
 0.37549235 8.90259048 1.27765998 5.94695691 6.53315793 1.8542774
 1.79750692 6.9517947  4.03132715 5.06340852 3.59561001 9.53295442]



[[1.82362019 0.04312125]
 [4.32395491 1.74324053]
 [7.09584695 4.57134785]
 [5.38736406 5.29680198]
 [9.80027554 8.2069501 ]
 [2.33240057 4.59454927]
 [0.37549235 8.90259048]
 [1.27765998 5.94695691]
 [6.53315793 1.8542774 ]
 [1.79750692 6.9517947 ]
 [4.03132715 5.06340852]
 [3.59561001 9.53295442]]



None


In [52]:
 a = array([1,2,3])
 b = a
 print( b is a )
 
 c = array([3,4])
 print( a is c )

True
False


In [59]:
# view() method creates a new array object that looks at the same data
# array objects are different but the data are same
# if you change value of a view array , the real array will change too

a = arange(10).reshape(2,5)
c = a.view()
print(c is a)
print("\n\n")
print(c.base is a)
print("\n\n")

c[0,1] = 1234      

print(a)

# The copy method makes a complete copy of the array and its data.

d = a.copy()

d[0,1] = 2000

print("\n\n")
print(a)


False



False



[[   0 1234    2    3    4]
 [   5    6    7    8    9]]



[[   0 1234    2    3    4]
 [   5    6    7    8    9]]


In [60]:
'''
Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace,
 logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like

Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item,
 newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

Questions
all, any, nonzero, where

Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

Basic Statistics
cov, mean, std, var

Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot

'''

'\nArray Creation\narange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace,\n logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like\n\nConversions\nndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat\n\nManipulations\narray_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item,\n newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack\n\nQuestions\nall, any, nonzero, where\n\nOrdering\nargmax, argmin, argsort, max, min, ptp, searchsorted, sort\n\nOperations\nchoose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum\n\nBasic Statistics\ncov, mean, std, var\n\nBasic Linear Algebra\ncross, dot, outer, linalg.svd, vdot\n\n'

In [66]:
nsteps = 1000
draws = random.randint(0, 2, size=nsteps)
draws.size
steps = where(draws > 0, 1, -1)
walk = steps.cumsum()
walk

array([  1,   0,   1,   0,   1,   2,   3,   2,   3,   4,   5,   4,   5,
         4,   3,   4,   5,   6,   7,   6,   7,   6,   7,   6,   5,   4,
         3,   4,   3,   2,   1,   2,   1,   2,   1,   0,  -1,   0,  -1,
         0,   1,   0,  -1,   0,  -1,  -2,  -3,  -2,  -1,   0,  -1,   0,
         1,   2,   3,   2,   3,   4,   5,   6,   5,   6,   7,   6,   7,
         8,   9,  10,   9,   8,   7,   8,   7,   8,   9,   8,   7,   6,
         7,   6,   7,   8,   9,   8,   9,  10,  11,  10,  11,  12,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  20,  21,  20,
        21,  22,  21,  20,  19,  18,  17,  18,  17,  18,  17,  18,  19,
        20,  21,  22,  21,  22,  23,  24,  25,  24,  25,  26,  27,  28,
        27,  26,  25,  24,  25,  26,  27,  26,  25,  24,  25,  26,  27,
        26,  27,  26,  27,  26,  25,  26,  25,  24,  25,  26,  25,  26,
        27,  26,  25,  26,  27,  26,  27,  26,  25,  26,  27,  26,  27,
        26,  27,  28,  29,  30,  29,  28,  29,  28,  27,  26,  2