In [1]:
from numpy import *

a = arange(0,15).reshape(3,5)
print(a , "\n")

print('shape = ' , shape(a) , "\n")
print('dimension = ', ndim(a), "\n")
print('size = ', size(a), "\n")
print('dtype = ', dtype(a[0,0]).name, "\n")
print('item size = ', a.itemsize, "\n ")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

shape =  (3, 5) 

dimension =  2 

size =  15 

dtype =  int64 

item size =  8 
 


In [37]:
print( zeros((3,5), float64), "\n" )

print( ones((3,5), float64), "\n" )

print( empty((4,5)) , "\n")

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[6.94720450e-310 6.94720450e-310 6.94720450e-310 6.94720450e-310
  6.94720449e-310]
 [6.94720450e-310 6.94720450e-310 6.94720450e-310 6.94720448e-310
  6.94720450e-310]
 [6.94720450e-310 6.94720450e-310 6.94720450e-310 6.94720450e-310
  6.94720066e-310]
 [4.00193173e-322 4.67841451e-310 6.94720429e-310 6.94720054e-310
  1.26593885e-281]] 



In [39]:
print(  arange(10,30,5,int64) , "\n")

print( linspace(0 , 2 , 10) , "\n")

[10 15 20 25] 

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ] 



In [ ]:
arange(4)